# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/hardware/network/broadcom-43xx.nix")
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  # Apple Keyboard Configuration 
  # https://wiki.archlinux.org/title/Apple_Keyboard#hid_apple_module_options
  # 
  # - Options are space sensitive! ex) "hid_apple.fnmode = 2" doesn't work
  # - hid_apple.fnmode=2: 0 = disabled; 1 = normally media keys, switchable to function keys by holding Fn key (Default); 2 = normally function keys, switchable to media keys by holding Fn key
  # - hid_apple.swap_fn_leftctrl=1: 0 = as silkscreened, Mac layout (Default); 1 = swapped, PC layout
  boot.kernelParams = [
    "hid_apple.fnmode=2" # 0 = disabled; 1 = normally media keys, switchable to function keys by holding Fn key (Default); 2 = normally function keys, switchable to media keys by holding Fn key
    "hid_apple.swap_fn_leftctrl=1" # 0 = as silkscreened, Mac layout (Default); 1 = swapped, PC layout
  ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/95317577-0a0f-4842-9648-f079d16ec6b4";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/67E3-17ED";
      fsType = "vfat";
    };

  swapDevices = [ ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  # high-resolution display
  hardware.video.hidpi.enable = lib.mkDefault true;
}
